In [4]:
import pandas as pd
from pathlib import Path

manifest = pd.read_csv("gdc_manifest.txt", sep= "\t")

manifest.head()

,id,filename,md5,size,state
0,744a6d3d-b666-49aa-8d26-47f34e3d1eb5,94027f46-390c-4dda-ab89-cb1ac0a291cd.rna_seq.a...,4a91710ffccd29966a3374ffaf14abec,4231952,released
1,4ecc1f1a-8ff4-4552-a5e8-7a9652b6d1d5,df45fb41-4511-4dab-b865-fcdfcda0400a.rna_seq.a...,af51e54b9dc2f6aecd39ab26d2b79824,4238832,released
2,1ace2a0c-773d-45b5-8fd6-968c88731bbb,c33ecc28-d5ba-4416-b93d-445b7883b6e8.rna_seq.a...,ff767304460d3385c372d7e0818cb45a,4239626,released
3,2d5b0962-b5c4-4482-9f28-47e4dcdb6df6,602e3d24-a45d-4fe4-9b70-a679d93f470d.rna_seq.a...,e55f74a99e6c797b03ecd3fdb43bc27a,4221019,released
4,84cff855-d17a-4c09-b432-53893ae69c1e,03d891b3-8faf-4384-94ce-2015f1ca5df0.rna_seq.a...,a047d3255bf04eed49d33a5f41787b6c,4217372,released

In [5]:
one_file_manifest = manifest.iloc[[0]]

one_file_manifest.to_csv(
    "data/metadata/gdc_manifest_one_file.txt",
    sep="\t",
    index=False
)

one_file_manifest

,id,filename,md5,size,state
0,744a6d3d-b666-49aa-8d26-47f34e3d1eb5,94027f46-390c-4dda-ab89-cb1ac0a291cd.rna_seq.a...,4a91710ffccd29966a3374ffaf14abec,4231952,released

In [6]:
count_files = list(Path("data/raw/star_counts").rglob("*.tsv"))

len(count_files), count_files[:3]

(1,
 [PosixPath('data/raw/star_counts/744a6d3d-b666-49aa-8d26-47f34e3d1eb5/94027f46-390c-4dda-ab89-cb1ac0a291cd.rna_seq.augmented_star_gene_counts.tsv')])

In [8]:
test_counts = pd.read_csv(count_files[0], sep="\t", comment="#")

test_counts.shape
test_counts.columns

Index(['gene_id', 'gene_name', 'gene_type', 'unstranded', 'stranded_first',
       'stranded_second', 'tpm_unstranded', 'fpkm_unstranded',
       'fpkm_uq_unstranded'],
      dtype='object')

In [9]:
test_counts.head(10)

,gene_id,gene_name,gene_type,unstranded,stranded_first,stranded_second,tpm_unstranded,fpkm_unstranded,fpkm_uq_unstranded
0,N_unmapped,NaN,NaN,1173926,1173926,1173926,NaN,NaN,NaN
1,N_multimapping,NaN,NaN,4517194,4517194,4517194,NaN,NaN,NaN
2,N_noFeature,NaN,NaN,2614368,24693271,24696884,NaN,NaN,NaN
3,N_ambiguous,NaN,NaN,4751629,1308522,1303037,NaN,NaN,NaN
4,ENSG00000000003.15,TSPAN6,protein_coding,426,213,213,6.7894,2.4124,2.4300
5,ENSG00000000005.6,TNMD,protein_coding,3,2,1,0.1469,0.0522,0.0526
6,ENSG00000000419.13,DPM1,protein_coding,1439,722,717,86.1885,30.6240,30.8480
7,ENSG00000000457.14,SCYL3,protein_coding,1049,861,830,11.0178,3.9148,3.9434
8,ENSG00000000460.17,C1orf112,protein_coding,326,511,506,3.9477,1.4027,1.4129
9,ENSG00000000938.13,FGR,protein_coding,1015,526,489,21.6964,7.7090,7.7654

In [10]:
test_counts.tail(10)

,gene_id,gene_name,gene_type,unstranded,stranded_first,stranded_second,tpm_unstranded,fpkm_unstranded,fpkm_uq_unstranded
60654,ENSG00000288661.1,AL451106.1,protein_coding,0,0,0,0.0000,0.0000,0.0000
60655,ENSG00000288662.1,AC092910.4,lncRNA,0,0,0,0.0000,0.0000,0.0000
60656,ENSG00000288663.1,AC073611.1,lncRNA,43,25,18,0.5455,0.1938,0.1952
60657,ENSG00000288665.1,AC136977.1,lncRNA,0,0,0,0.0000,0.0000,0.0000
60658,ENSG00000288667.1,AC078856.1,lncRNA,0,0,0,0.0000,0.0000,0.0000
60659,ENSG00000288669.1,AC008763.4,protein_coding,0,0,0,0.0000,0.0000,0.0000
60660,ENSG00000288670.1,AL592295.6,lncRNA,297,152,161,11.8821,4.2219,4.2528
60661,ENSG00000288671.1,AC006486.3,protein_coding,0,0,0,0.0000,0.0000,0.0000
60662,ENSG00000288674.1,AL391628.1,protein_coding,6,5,1,0.0451,0.0160,0.0161
60663,ENSG00000288675.1,AP006621.6,protein_coding,34,24,23,1.4631,0.5198,0.5237

In [11]:
signature_genes = {
    "t_cell_presence": ["CD3D", "CD3E", "CD3G", "TRAC", "TRBC1"],
    "cytotoxic_activity": ["PRF1", "GZMB", "GZMH", "NKG7", "CTSW"],
    "fibroblast_presence": ["DCN", "LUM", "COL1A1", "COL1A2", "COL3A1"],
    "caf_matrix": ["FAP", "COL11A1", "POSTN", "CTHRC1", "MMP11"],
    "secondary_activation": ["IFNG"],
}

all_signature_genes = sorted({gene for genes in signature_genes.values() for gene in genes})

test_counts[test_counts["gene_name"].isin(all_signature_genes)][
    ["gene_id", "gene_name", "gene_type", "unstranded", "tpm_unstranded"]
]

,gene_id,gene_name,gene_type,unstranded,tpm_unstranded
305,ENSG00000011465.18,DCN,protein_coding,13308,74.3431
825,ENSG00000060718.22,COL11A1,protein_coding,2006,15.9520
1413,ENSG00000078098.14,FAP,protein_coding,946,9.8147
2144,ENSG00000099953.10,MMP11,protein_coding,7602,106.7335
2320,ENSG00000100450.13,GZMH,protein_coding,205,15.5837
2321,ENSG00000100453.13,GZMB,protein_coding,675,34.5838
3095,ENSG00000105374.10,NKG7,protein_coding,994,78.0230
3595,ENSG00000108821.14,COL1A1,protein_coding,98047,786.9552
3909,ENSG00000111537.5,IFNG,protein_coding,62,3.7012
6720,ENSG00000133110.15,POSTN,protein_coding,34917,461.9789
7813,ENSG00000139329.5,LUM,protein_coding,12257,331.7464
10511,ENSG00000160654.11,CD3G,protein_coding,407,7.6703
11418,ENSG00000164692.18,COL1A2,protein_coding,75279,503.1099
11481,ENSG00000164932.13,CTHRC1,protein_coding,1402,58.0829
12065,ENSG00000167286.10,CD3D,protein_coding,599,56.3114
12388,ENSG00000168542.16,COL3A1,protein_coding,76832,821.9016
13335,ENSG00000172543.8,CTSW,protein_coding,376,16.0746
14898,ENSG00000180644.8,PRF1,protein_coding,1598,45.8793
17907,ENSG00000198851.10,CD3E,protein_coding,1902,51.7116
21585,ENSG00000211751.9,TRBC1,TR_C_gene,1015,96.5491
54467,ENSG00000277734.8,TRAC,TR_C_gene,2300,170.0141

In [12]:
present_genes = set(test_counts["gene_name"].dropna())

missing_genes = sorted(set(all_signature_genes) - present_genes)

missing_genes

[]

In [13]:
gene_counts_one = (
    test_counts
    .loc[~test_counts["gene_id"].str.startswith("N_")]
    .copy()
)

gene_counts_one.shape

(60660, 9)

In [15]:
gene_counts_one.head()

,gene_id,gene_name,gene_type,unstranded,stranded_first,stranded_second,tpm_unstranded,fpkm_unstranded,fpkm_uq_unstranded
4,ENSG00000000003.15,TSPAN6,protein_coding,426,213,213,6.7894,2.4124,2.4300
5,ENSG00000000005.6,TNMD,protein_coding,3,2,1,0.1469,0.0522,0.0526
6,ENSG00000000419.13,DPM1,protein_coding,1439,722,717,86.1885,30.6240,30.8480
7,ENSG00000000457.14,SCYL3,protein_coding,1049,861,830,11.0178,3.9148,3.9434
8,ENSG00000000460.17,C1orf112,protein_coding,326,511,506,3.9477,1.4027,1.4129